import { Injectable } from '@angular/core';

import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root',
})
export class EmployeeService {
  getData() {
    return [
      {
        ID: 1,
        EMPLOYEECODE: 'NV00000001',
        FIRSTNAME: 'Hà Phú',
        FULLNAME: 'Toàn',
        COMMONNAME: 'Tony IT',
        GENDER: true,
        IMAGES: 'z4536063537611_b71410afc9987745ea24b1a9ff83f4e8.jpg',
        BIRTHDAY: '1991-08-18T17:00:00.000Z',
        PLACEOFBIRTH: 'An Long, Tam Nông,Đồng Tháp',
        MARRIED: false,
        ADDRESS: 'Đường Tống Văn Lê , Ấp Tân Phú 2 , xã Tân Lý Đông',
        ADDRESSTMP: 'Nguyễn văn Tăng, Quận 9 , TPHCM',
        PHONE: '0955667788',
        EMAIL: 'haphutoan@gmail.com',
        CCCD: '34334428983',
        DATECCCD: '2008-05-26T17:00:00.000Z',
        ISSUEDBY: 'Đồng Tháp',
        DATESTARTWORD: '2023-07-02T17:00:00.000Z',
        HEALTH: 'Ổn định',
        HEIGHT: 163,
        WEIGHT: 58,
        STATUSWORK: 1,
        NATIONALITYID: 1,
        NATIONID: 2,
        RELIGIONID: 1,
        DEGREEID: 3,
        FOREIGNID: '1,4',
        BHXH: true,
        BHYT: true,
        BHTN: true,
        UNIONDUES: true,
        NOTE: 'Làm việc tại công ty Bentley Designs',
        MARITALID: 2,
        AUTHORITY: true,
        COMMENT: null,
        DEPARTMENT: {
          ID: 1,
          NAMEDEPARTMENTVN: 'Công nghệ thông tin',
          NAMEDEPARTMENTEN: 'IT',
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        POSITION: {
          ID: 5,
          POSITIONNAMEVN: 'Trưởng phòng',
          POSITIONNAMEEN: 'Manager',
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        COMPANYID: 1,
        NOBHXH: '909999999',
        DATEBHXH: '2009-01-31T17:00:00.000Z',
        ISSUEBYBHXH: 'Thủ Đức',
        NOBHYT: '1234567',
        FROMDATEBHYT: '2023-07-24T17:00:00.000Z',
        TODATEBHYT: '2023-07-25T17:00:00.000Z',
        PROVINCEBHYT: 'Tiền giang',
        HOPITALBHYT: 'BV Đa khoa tỉnh Tiền Giang',
        ISACTIVE: true,
        LEADERID: 1,
        MANAGERID: 1,
        SALARY: 8000000,
        CREATEDBYUSER: 'sys_user',
        CREATEDBYDATE: '2023-10-19T14:21:56.000Z',
        DATEUPDATED: null,
        USERLASTUPDATED: null,
      },
      {
        ID: 2,
        EMPLOYEECODE: 'NV00000002',
        FIRSTNAME: 'Lê Thị Cẩm',
        FULLNAME: 'Tú',
        COMMONNAME: 'Lovely',
        GENDER: false,
        IMAGES: 'IWVN.ico',
        BIRTHDAY: '1991-08-13T17:00:00.000Z',
        PLACEOFBIRTH: 'Tiền Giang',
        MARRIED: false,
        ADDRESS: 'Cai lậy - Tiền Giang',
        ADDRESSTMP: 'Tân Uyên, Bình Dương',
        PHONE: '0366828282',
        EMAIL: 'tu@gmail.com.vn',
        CCCD: '123456789',
        DATECCCD: '2010-05-11T17:00:00.000Z',
        ISSUEDBY: 'Đồng Nai',
        DATESTARTWORD: '2012-05-01T17:00:00.000Z',
        HEALTH: 'To khỏe',
        HEIGHT: 168,
        WEIGHT: 65,
        STATUSWORK: 1,
        NATIONALITYID: 1,
        NATIONID: 3,
        RELIGIONID: 1,
        DEGREEID: 6,
        FOREIGNID: true,
        BHXH: true,
        BHYT: true,
        BHTN: true,
        UNIONDUES: true,
        NOTE: 'Ở nhà chăm con',
        MARITALID: 1,
        AUTHORITY: true,
        COMMENT: null,
        DEPARTMENT: {
          ID: 2,
          NAMEDEPARTMENTVN: 'Phòng CS',
          NAMEDEPARTMENTEN: 'CS-CR',
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        POSITION: {
          ID: 11,
          POSITIONNAMEVN: 'Nhân viên',
          POSITIONNAMEEN: null,
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        COMPANYID: 1,
        NOBHXH: '0909999999',
        DATEBHXH: '2010-07-30T17:00:00.000Z',
        ISSUEBYBHXH: 'Tiền Giang',
        NOBHYT: '01234567',
        FROMDATEBHYT: '2023-07-30T17:00:00.000Z',
        TODATEBHYT: '2023-07-30T17:00:00.000Z',
        PROVINCEBHYT: 'Châu Thành',
        HOPITALBHYT: 'BV Đa khoa tỉnh Tiền Giang',
        ISACTIVE: true,
        LEADERID: 1,
        MANAGERID: 1,
        SALARY: 8000000,
        CREATEDBYUSER: 'sys_user',
        CREATEDBYDATE: '2023-10-19T14:21:56.000Z',
        DATEUPDATED: null,
        USERLASTUPDATED: null,
      },
      {
        ID: 3,
        EMPLOYEECODE: 'NV00000003',
        FIRSTNAME: 'Nguyễn Thị Kim',
        FULLNAME: 'Thanh',
        COMMONNAME: 'Lisa',
        GENDER: false,
        IMAGES: null,
        BIRTHDAY: '1991-06-21T17:00:00.000Z',
        PLACEOFBIRTH: 'Đồng Nai',
        MARRIED: false,
        ADDRESS: 'Đồng Nai',
        ADDRESSTMP: 'Long Bình - Đồng Nai',
        PHONE: '0123123123',
        EMAIL: 'thanh@gmail.com',
        CCCD: '123456789',
        DATECCCD: '2012-04-10T17:00:00.000Z',
        ISSUEDBY: 'Đồng Nai',
        DATESTARTWORD: '2012-05-01T17:00:00.000Z',
        HEALTH: 'Gầy quá đi',
        HEIGHT: 158,
        WEIGHT: 43,
        STATUSWORK: 1,
        NATIONALITYID: 1,
        NATIONID: 2,
        RELIGIONID: 2,
        DEGREEID: 6,
        FOREIGNID: '2,3',
        BHXH: true,
        BHYT: true,
        BHTN: true,
        UNIONDUES: true,
        NOTE: 'Đi xe đưa rước',
        MARITALID: 2,
        AUTHORITY: true,
        COMMENT: null,
        DEPARTMENT: {
          ID: 3,
          NAMEDEPARTMENTVN: 'Phòng Nhân Sự',
          NAMEDEPARTMENTEN: 'HR-CB',
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        POSITION: {
          ID: 5,
          POSITIONNAMEVN: 'Trưởng phòng',
          POSITIONNAMEEN: 'Manager',
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        COMPANYID: 2,
        NOBHXH: null,
        DATEBHXH: null,
        ISSUEBYBHXH: null,
        NOBHYT: null,
        FROMDATEBHYT: null,
        TODATEBHYT: null,
        PROVINCEBHYT: null,
        HOPITALBHYT: null,
        ISACTIVE: true,
        LEADERID: 1,
        MANAGERID: 1,
        SALARY: 8500000,
        CREATEDBYUSER: 'sys_user',
        CREATEDBYDATE: '2023-10-19T14:21:56.000Z',
        DATEUPDATED: null,
        USERLASTUPDATED: null,
      },
      {
        ID: 4,
        EMPLOYEECODE: 'NV00000004',
        FIRSTNAME: 'Nguyễn Thị Thu',
        FULLNAME: 'Kim',
        COMMONNAME: 'Mansy',
        GENDER: false,
        IMAGES: null,
        BIRTHDAY: '1991-04-17T17:00:00.000Z',
        PLACEOFBIRTH: 'Đồng Nai',
        MARRIED: false,
        ADDRESS: 'Biên Hòa - Đồng Nai',
        ADDRESSTMP: 'Tân Uyên, Bình Dương',
        PHONE: '321634645',
        EMAIL: 'canhhongruclua@yahoo.com',
        CCCD: '132135465',
        DATECCCD: '2012-04-30T17:00:00.000Z',
        ISSUEDBY: 'Đồng Nai',
        DATESTARTWORD: '2012-05-04T17:00:00.000Z',
        HEALTH: 'Gấy quá đi ah',
        HEIGHT: 156,
        WEIGHT: 42,
        STATUSWORK: 1,
        NATIONALITYID: 1,
        NATIONID: 4,
        RELIGIONID: 2,
        DEGREEID: 6,
        FOREIGNID: '1,4',
        BHXH: true,
        BHYT: true,
        BHTN: true,
        UNIONDUES: false,
        NOTE: 'Nhân viên gương mẫu',
        MARITALID: 2,
        AUTHORITY: true,
        COMMENT: null,
        DEPARTMENT: {
          ID: 4,
          NAMEDEPARTMENTVN: 'Phòng Mẫu',
          NAMEDEPARTMENTEN: 'Sample',
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        POSITION: {
          ID: 5,
          POSITIONNAMEVN: 'Trưởng phòng',
          POSITIONNAMEEN: 'Manager',
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        COMPANYID: 1,
        NOBHXH: null,
        DATEBHXH: null,
        ISSUEBYBHXH: null,
        NOBHYT: null,
        FROMDATEBHYT: null,
        TODATEBHYT: null,
        PROVINCEBHYT: null,
        HOPITALBHYT: null,
        ISACTIVE: true,
        LEADERID: 1,
        MANAGERID: 1,
        SALARY: 4500000,
        CREATEDBYUSER: 'sys_user',
        CREATEDBYDATE: '2023-10-19T14:21:56.000Z',
        DATEUPDATED: null,
        USERLASTUPDATED: null,
      },
      {
        ID: 5,
        EMPLOYEECODE: 'NV00000005',
        FIRSTNAME: 'Vũ Quốc',
        FULLNAME: 'Hòa',
        COMMONNAME: 'Kay',
        GENDER: false,
        IMAGES: 'IWVN.ico',
        BIRTHDAY: '1991-10-08T17:00:00.000Z',
        PLACEOFBIRTH: 'Hải Dương',
        MARRIED: false,
        ADDRESS: 'Long Bình - Biên Hòa - Đồng Nai',
        ADDRESSTMP: 'Tân Uyên, Bình Dương',
        PHONE: '0123456789',
        EMAIL: 'hoa@gmail.com',
        CCCD: '132465465',
        DATECCCD: '2012-04-30T17:00:00.000Z',
        ISSUEDBY: 'Hải Dương',
        DATESTARTWORD: '2012-05-04T17:00:00.000Z',
        HEALTH: 'Very Good',
        HEIGHT: 160,
        WEIGHT: 54,
        STATUSWORK: 1,
        NATIONALITYID: 1,
        NATIONID: 3,
        RELIGIONID: 2,
        DEGREEID: 6,
        FOREIGNID: null,
        BHXH: true,
        BHYT: true,
        BHTN: true,
        UNIONDUES: false,
        NOTE: null,
        MARITALID: 1,
        AUTHORITY: true,
        COMMENT: null,
        DEPARTMENT: {
          ID: 5,
          NAMEDEPARTMENTVN: 'Kho',
          NAMEDEPARTMENTEN: 'Warehouse',
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        POSITION: {
          ID: 6,
          POSITIONNAMEVN: 'Phó phòng',
          POSITIONNAMEEN: null,
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        COMPANYID: 1,
        NOBHXH: null,
        DATEBHXH: null,
        ISSUEBYBHXH: null,
        NOBHYT: null,
        FROMDATEBHYT: null,
        TODATEBHYT: null,
        PROVINCEBHYT: null,
        HOPITALBHYT: null,
        ISACTIVE: true,
        LEADERID: 1,
        MANAGERID: 1,
        SALARY: 7500000,
        CREATEDBYUSER: 'sys_user',
        CREATEDBYDATE: '2023-10-19T14:21:56.000Z',
        DATEUPDATED: null,
        USERLASTUPDATED: null,
      },
      {
        ID: 6,
        EMPLOYEECODE: 'NV00000006',
        FIRSTNAME: 'Lê',
        FULLNAME: 'Minh Châu',
        COMMONNAME: 'Tom',
        GENDER: false,
        IMAGES: 'logo.png',
        BIRTHDAY: '1991-08-24T17:00:00.000Z',
        PLACEOFBIRTH: 'Đồng Nai',
        MARRIED: false,
        ADDRESS: 'Đường Tống Văn Lê , Ấp Tân Phú 2 , xã Tân Lý Đông',
        ADDRESSTMP: 'Tân Uyên, Bình Dương',
        PHONE: '0972838671',
        EMAIL: 'haphutoanit@gmail.com',
        CCCD: '113246544',
        DATECCCD: '2012-05-01T17:00:00.000Z',
        ISSUEDBY: 'Đồng Nai',
        DATESTARTWORD: '2012-05-04T17:00:00.000Z',
        HEALTH: 'Cực kỳ tốt',
        HEIGHT: 163,
        WEIGHT: 56,
        STATUSWORK: 1,
        NATIONALITYID: 1,
        NATIONID: 1,
        RELIGIONID: 1,
        DEGREEID: 6,
        FOREIGNID: null,
        BHXH: true,
        BHYT: true,
        BHTN: true,
        UNIONDUES: true,
        NOTE: null,
        MARITALID: 2,
        AUTHORITY: true,
        COMMENT: null,
        DEPARTMENT: {
          ID: 6,
          NAMEDEPARTMENTVN: 'Truyền thông',
          NAMEDEPARTMENTEN: 'Marketing',
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        POSITION: {
          ID: 7,
          POSITIONNAMEVN: 'Trưởng Ban Kiểm Soát',
          POSITIONNAMEEN: null,
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        COMPANYID: 2,
        NOBHXH: null,
        DATEBHXH: null,
        ISSUEBYBHXH: null,
        NOBHYT: null,
        FROMDATEBHYT: null,
        TODATEBHYT: null,
        PROVINCEBHYT: null,
        HOPITALBHYT: null,
        ISACTIVE: true,
        LEADERID: 1,
        MANAGERID: 1,
        SALARY: 8500000,
        CREATEDBYUSER: 'sys_user',
        CREATEDBYDATE: '2023-10-19T14:21:56.000Z',
        DATEUPDATED: null,
        USERLASTUPDATED: null,
      },
      {
        ID: 7,
        EMPLOYEECODE: 'NV00000007',
        FIRSTNAME: 'Nguyễn Hoàng',
        FULLNAME: 'Tú',
        COMMONNAME: 'Anna',
        GENDER: true,
        IMAGES: 'z4627786454789_8c2f4b939bdf24386e71b5166bf3bf9a.jpg',
        BIRTHDAY: '1990-05-16T17:00:00.000Z',
        PLACEOFBIRTH: 'Đồng Nai',
        MARRIED: false,
        ADDRESS: 'Đường Tống Văn Lê , Ấp Tân Phú 2 , xã Tân Lý Đông',
        ADDRESSTMP: 'Tân Uyên, Bình Dương',
        PHONE: '03344558832',
        EMAIL: 'hatheduy@gmail.com',
        CCCD: '123456479',
        DATECCCD: '2010-05-18T17:00:00.000Z',
        ISSUEDBY: 'Đồng Nai',
        DATESTARTWORD: '2012-05-10T17:00:00.000Z',
        HEALTH: 'To nhưng không khỏe cho lắm',
        HEIGHT: 165,
        WEIGHT: 65,
        STATUSWORK: 1,
        NATIONALITYID: 1,
        NATIONID: 1,
        RELIGIONID: 2,
        DEGREEID: 6,
        FOREIGNID: true,
        BHXH: true,
        BHYT: true,
        BHTN: true,
        UNIONDUES: false,
        NOTE: 'sdfasdf',
        MARITALID: 3,
        AUTHORITY: true,
        COMMENT: null,
        DEPARTMENT: {
          ID: 7,
          NAMEDEPARTMENTVN: 'Kế toá',
          NAMEDEPARTMENTEN: 'Accounting',
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        POSITION: {
          ID: 8,
          POSITIONNAMEVN: 'Quản lý',
          POSITIONNAMEEN: null,
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        COMPANYID: 2,
        NOBHXH: null,
        DATEBHXH: null,
        ISSUEBYBHXH: null,
        NOBHYT: null,
        FROMDATEBHYT: null,
        TODATEBHYT: null,
        PROVINCEBHYT: null,
        HOPITALBHYT: null,
        ISACTIVE: true,
        LEADERID: 1,
        MANAGERID: 1,
        SALARY: 14500000,
        CREATEDBYUSER: 'sys_user',
        CREATEDBYDATE: '2023-10-19T14:21:56.000Z',
        DATEUPDATED: null,
        USERLASTUPDATED: null,
      },
      {
        ID: 8,
        EMPLOYEECODE: 'NV00000009',
        FIRSTNAME: 'Hoàng Bảo',
        FULLNAME: 'Ngọc',
        COMMONNAME: 'Waana Saka',
        GENDER: true,
        IMAGES: 'Iconmoon-Web-Application-Profile.32.png',
        BIRTHDAY: '1993-11-03T17:00:00.000Z',
        PLACEOFBIRTH: 'Đồng Nai',
        MARRIED: false,
        ADDRESS: 'Biên Hòa - Đồng Nai',
        ADDRESSTMP: 'Tân Uyên, Bình Dương',
        PHONE: '01688786834',
        EMAIL: 'itw@gmail.com',
        CCCD: '123456798',
        DATECCCD: '2008-05-14T17:00:00.000Z',
        ISSUEDBY: 'Đồng Nai',
        DATESTARTWORD: '2012-05-25T17:00:00.000Z',
        HEALTH: 'Gầy lắm',
        HEIGHT: 160,
        WEIGHT: 50,
        STATUSWORK: 1,
        NATIONALITYID: 1,
        NATIONID: 1,
        RELIGIONID: 1,
        DEGREEID: 6,
        FOREIGNID: '1,2,3,4',
        BHXH: true,
        BHYT: true,
        BHTN: true,
        UNIONDUES: false,
        NOTE: 'Nhân viên này có tiền sử bệnh tim',
        MARITALID: 1,
        AUTHORITY: true,
        COMMENT: null,
        DEPARTMENT: {
          ID: 8,
          NAMEDEPARTMENTVN: 'Vận hành Sản xuất',
          NAMEDEPARTMENTEN: 'Production Control',
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        POSITION: {
          ID: 9,
          POSITIONNAMEVN: 'Ca trưởng bảo vệ',
          POSITIONNAMEEN: null,
          ISACTIVE: true,
          DATECREATED: '2023-10-19T14:21:56.000Z',
          USERCREATED: 'sys_user',
          DATEUPDATED: null,
          USERUPDATED: null,
        },
        COMPANYID: 1,
        NOBHXH: null,
        DATEBHXH: null,
        ISSUEBYBHXH: null,
        NOBHYT: '01234567',
        FROMDATEBHYT: '2023-08-30T17:00:00.000Z',
        TODATEBHYT: '2023-08-31T17:00:00.000Z',
        PROVINCEBHYT: null,
        HOPITALBHYT: null,
        ISACTIVE: true,
        LEADERID: 2,
        MANAGERID: 3,
        SALARY: 9800000,
        CREATEDBYUSER: 'sys_user',
        CREATEDBYDATE: '2023-10-19T14:21:56.000Z',
        DATEUPDATED: null,
        USERLASTUPDATED: null,
      },
    ];
  }

  constructor(private http: HttpClient) {}
}
